Revert "add skipnav link in header"
edx/frontend-component-header pull request #96
Opened 2021-03-19 16:03 UTC by uzairr

Reverts edx/frontend-component-header#95

2021-03-19 16:04 UTC, adeelehsan approved these changes

2021-06-12 06:26 UTC, stvstnfrd commented
@uzairr @adeelehsan Do we still need this? What's the context?

2021-08-09 23:22 UTC, stvstnfrd requested changes
@uzairr @adeelehsan Do you mind if I close this?

Let me know if it's still needed, but I'm hoping to do some PR cleanup :)

2021-08-10 19:18 UTC, stvstnfrd commented
Feel free to re-open if/when you're ready!

2021-08-10 19:18 UTC, closed without merging